### PR TITLE
[android] add ACCESS_MEDIA_LOCATION to blacklist for android permissions

### PR DESCRIPTION
**Pull request by ajsmth**
# Why

related to this PR: https://github.com/expo/expo/pull/14413

Adding this permission to Expo Go to enable location exif data for Android 10+

# How

Adding the string to this blacklist to be stripped unless otherwise specified by a given Expo project

# Test Plan

I would like feedback on how to test this - I think producing a build and inspecting the permissions / manifest would be the best way

### CODE REVIEW

**Comment by brentvatne** [comment]
i believe you can test this by updating @expo/xdl in the `tools` directory in `expo/expo`. you can alternatively just make this change directly in `node_modules` in `expo/expo` so you don't need to publish anything.

after that, follow the standard process for building an android standalone app within the repo and inspect the resulting apk to ensure the permissions are what you expect. you can use `apktool` to extract the apk

**Comment by ajsmth** [comment]
confirmed with local turtle build that this permission is stripped from the AndroidManifest

**Review by byCedric — APPROVED** [review]

**Comment by byCedric** [comment]
Awesome! Thanks for doing the extra XDL step 😄

**Comment by brentvatne** [comment]
once we land this we need to publish and then update the xdl version in expo/expo and expo/turtle :)

**Review by brentvatne — APPROVED** [review]

**Pull request merged**
