### PR TITLE
Support Android intent filters in app.json

### PR DESCRIPTION
**Pull request by mbillard**
Allows developers to specify an array of `intentFilters` in the `android` part of `app.json`.

```json
{
  "expo": {
    ...
    "android": {
      "intentFilters": [
        {
          "action": "VIEW",
          "data": {
            "scheme": "https",
            "host": "*.expo.io"
          },
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
    },
    ...
  }
}
```

As discussed here: https://forums.expo.io/t/support-for-android-deep-linking/10534/3

Companion PR for the `AndroidManifest.xml` template: https://github.com/expo/expo/pull/2056

Will fulfill some feature requests on Canny as well:

* https://expo.canny.io/feature-requests/p/intent-filter-linking-specify-file-types-that-can-be-open-with-app
* https://expo.canny.io/feature-requests/p/intentlauncherandroid

### CODE REVIEW

**Comment by mbillard** [comment]
cc. @schneidmaster

**Review by esamelson — CHANGES_REQUESTED** [review]
Hi @mbillard! Thanks very much for your PRs, and sorry for the slow followup on our end. This looks great -- thanks especially for adding test coverage -- just a few small changes that need to happen before we can merge.

- Detached apps need to have these intent-filters in `MainActivity` rather than `ShellAppActivity`, so you'll need to add a second placeholder in your other PR and make sure to use the correct one here (you can see other examples of this in the AndroidShellApp script).
- Could you add some more detailed validation of the possible array items in the JSON schema file?
- Not a blocker but it would be reeeallllly helpful if you could also add some docs for this feature here https://github.com/expo/expo-docs , even if it's just a small section on the "Configuration with app.json" page.

Sorry for the multiple repos 😞 we're working on making it easier to send us PRs, but thanks for bearing with us in the meantime!

**Comment by mbillard** [comment]
Hi @esamelson, thanks for the feedback.

I added the second placeholder with logic to replace the appropriate one.

I also added some validation but I'm not familiar with the expected format, is it using https://github.com/hapijs/joi ? It looks different than the documentation but I mostly looked at how other keys were configured so maybe I did it correctly.

Finally, I'll be happy to update the docs. However it doesn't seem like there's anything for v29 and I would assume that's where this work would end up, am I correct? I can change v28 or unversioned but I'm not sure what your workflow is here.

Let me know, thanks!

**Comment by esamelson** [comment]
Hi @mbillard - thanks for the very fast response! This all looks great at a glance, so I'll try and get this all merged in soon.

Hmmm, interesting about the docs repo -- looks like our expbot has been failing to sync changes for the last 2 months 😮 we'll see about fixing that. Thanks for pointing it out!!

**Comment by mbillard** [comment]
Let me know when the docs repo is fixed, I'll gladly submit a PR for v29 (or whatever version you prefer).

**Comment by esamelson** [comment]
Thanks @mbillard ! Our docs repo is fixed now, so if you could add some documentation to both the `unversioned` and `v29` directories that would be super great.

**Pull request closed without merging**
