### PR TITLE
Remove dependency on macOS in order to detach

### PR DESCRIPTION
**Pull request by davidthornton**
Currently, `exp detach` has a dependency on macOS in order to build iOS binaries. The current behaviour that is exhibited when `exp detach` is run on a platform other than `darwin`, is that the user is asked to make an election between exiting and building a (binary ready) project for `android`.

It turns out that the only (hard) dependency that `exp detach` has on macOS in order to build `ios` binary-ready projects is the need to run `plutil`. The tool is spawned as a native process in order to convert plist files from XML format to JSON and vice versa.

This pull request replaces that dependency with an npm package which is able to replicate the results of spawning a macOS binary.

NOTE: the detachment process also calls `sips` (scriptable image processing system) which is, again, a macOS binary - but this is used solely to resize icon assets - and its failure to run is not fatal to either the detachment process or the building of an `ios` binary in Xcode; it merely triggers a warning.

Furthermore, not only does this improve the elegance of the detachment process, but it allows the entire process to be containerized (using Docker or a similar containerization tool). This in turn allows, for instance, CI servers to build assets offline and upload them to a distribution server, ready for releases to be cut and published to the app stores.

If you'd like me to replace calls to `sips`, or make any other changes before merging this pull request, just let me know and I will endeavour to push them as soon as I can!

### CODE REVIEW

**Comment by terribleben** [comment]
Thanks, this looks great!

I think we still warn to warn users who are trying to detach outside of macOS, because many of our users don't realize they'll be unable to easily build the resulting Xcode project. We'd like to help them avoid ending up angry/surprised/confused when they figure it out later.

**Comment by davidthornton** [comment]
Users will now be warned when attempting to detach outside of macOS.

**Comment by terribleben** [comment]
Thanks! Merged :)

**Comment by terribleben** [comment]
I ran into issues trying to use this code against compiled plist files, which we need to support. I didn't see anything about the npm plist library supporting these when I looked.

As a result I ended up doing [this](https://github.com/expo/xdl/commit/c7f773e0d16945a40cf88517eb8d3e7fd4291bdc#diff-777ffe2c4bb9f6b44005c4a6b5bf28bdR29), which basically restores the old behavior but only on macOS. Hopefully that still works for you.

**Pull request closed without merging**
